name: test,style check
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
jobs:
    vitest-test:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Test'
              run: npx vitest --coverage.enabled true
            - name: 'Report Coverage'
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
    code-check:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
          contents: read
          pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Check'
              uses: mongolyy/reviewdog-action-biome@v1
              with:
                github_token: ${{ secrets.github_token }}
                reporter: github-pr-review
                level: error
                fail_level: error
